# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [127]:
import numpy as np

2. Create a null vector of size 10 

In [131]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [132]:
a=np.arange(10,50)
a


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [136]:
a.shape


(40,)

5. Print the type of the previous array in question 3

In [135]:
a.dtype


dtype('int32')

6. Print the numpy version and the configuration


In [8]:
np.__version__

'1.19.2'

7. Print the dimension of the array in question 3


In [137]:
a.ndim

1

8. Create a boolean array with all the True values

In [139]:
bool_arr = np.ones(10, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [140]:
a=np.array([[1,2],[5,6]])
a


array([[1, 2],
       [5, 6]])

10. Create a three dimensional array



In [141]:
b=np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [142]:
list_of_numbers= np.array([1,2,3,4,5]) 
res= list_of_numbers[::-1]
res

array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [144]:
a=np.zeros(10) #Create a null vector of size 10 but the fifth value which is 1
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [146]:
c_matrix=np.identity(3)
c_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [147]:
arr=np.array([1,2,3,4,5])
arr=arr.astype('float64')
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [148]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr3= arr1 * arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [149]:
arr4=arr1>arr2
arr4

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [150]:
a=np.array([0,1,2,3,4,5,6,7,8,9])  
a[a%2==1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [152]:
a[a%2==1]= -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [154]:
arr[5:12]= 7
arr

array([1., 2., 3., 4., 5.])

20. Create a 2d array with 1 on the border and 0 inside

In [155]:
a= np.ones((5,5)) 
a[1:-1, 1:-1]= 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [156]:
arr2d[1][1]=12
arr2d

array([[-1.64515051, -1.48599451, -0.51043832],
       [-1.12993745, 12.        , -0.97331397],
       [-1.11690798, -0.54685572,  1.97291028],
       [ 1.56790233, -0.64419093, -1.0346948 ],
       [ 1.24041855, -0.12666287,  1.766375  ]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [157]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d


array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [158]:
arr2d=np.arange(0,9).reshape(3,3)
y=arr2d[0]
y

array([0, 1, 2])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [159]:
arr_2d=np.arange(0,9).reshape(3,3)
z=arr_2d[1,1]
z

4

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [160]:
arr2d=np.arange(0,9).reshape(3,3)
y=arr2d[0:2, 2:]
y

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [48]:
arr_10=np.random.random ((10,10))
min_1 , max_1= arr_10.min(), arr_10.max()
min_1, max_1

(0.00952407785639986, 0.9756250336001187)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [161]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a, b)) 


[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [162]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(np.in1d(a, b)))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [126]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
    

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [163]:
arr2d= np.random.randn(1,15).reshape(5,3)
arr2d

array([[ 0.23412729,  0.74574485,  1.70735403],
       [-1.36281003, -0.39933248,  0.89961717],
       [-0.42838229, -2.71704905,  0.05479155],
       [-0.80881051,  0.47109383, -1.60841484],
       [ 0.11864164, -0.31313675,  0.09560276]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [164]:
arr3d=np.random.randn(1,16).reshape(2,2,4)
arr3d

array([[[-0.25006023, -2.50561962, -0.06610058, -0.79425476],
        [-1.6079422 ,  0.94418848, -0.25967689,  0.55085628]],

       [[-2.32575163,  0.27982492, -0.82127526, -1.0730118 ],
        [-0.23793874, -0.31674695,  0.59790537, -0.6414754 ]]])

33. Swap axes of the array you created in Question 32

In [165]:
arr3d=np.random.randn(1,16).reshape(2,4,2)
arr3d

array([[[ 1.15669861,  0.13407017],
        [-0.17317647,  1.61447845],
        [-1.3931856 ,  1.00539682],
        [-1.48827644, -0.03406921]],

       [[ 1.09865961, -0.02536326],
        [ 0.62256196,  0.85140306],
        [-0.71393385,  1.24405963],
        [ 0.26192961, -1.42449723]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [166]:
arr_1= np.arange(10)
b=(np.sqrt(arr_1))
np.where(b<0.5,0, b)



array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [98]:
a= np.random.randn(12)
b= np.random.randn(12)
c, d=a.max(), b.max()
e=np.array([c,d])
e

array([1.22607003, 1.67700447])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [167]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names=set(names)
names

{'Bob', 'Joe', 'Will'}

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [168]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)


array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [120]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.delete(sampleArray , 1, axis = 1)
newColumn = np.array([[10,10,10]])
sampleArray=np.insert(sampleArray,1, newColumn, axis=1)


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [169]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]]).reshape(2,3)
z=(x*y)
z

array([[ 6., 46., -3.],
       [28., 40., 54.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [170]:
a=np.random.randn(20)
print(np.cumsum(a))

[ 2.20643582  1.63016167  1.70250541  1.5426102   0.36956097 -0.6198331
  0.18803501 -1.67752877 -2.04126345 -2.69490902 -1.34782332 -1.48935078
 -1.46583319 -2.01636377 -1.85588189 -2.9040983  -1.09759483 -0.30284361
  0.25164604  0.57050346]
