# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
a=np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
a.reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [8]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
y=np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [10]:
x=np.array([[0,1,2,3,4],[5,6,7,8,9]])
y=np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.hstack((x,y))


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [12]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
n=np.unique(a)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [22]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
b=a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [24]:
c=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
d=c.reshape(5,3)
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [29]:
e=np.arange(5*5)
b=np.square(e)
b

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576],
      dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [37]:
a=np.random.random((5,6))
b=np.mean(a)
b

0.5524147021351679

## Question:9

### Find the standard deviation of the previous array in Q8?

In [38]:

c=np.std(a)
c

0.2865782513827759

## Question:10

### Find the median of the previous array in Q8?

In [39]:
e=np.median(a)
e

0.587826832730076

## Question:11

### Find the transpose of the previous array in Q8?

In [41]:
f=np.transpose(a)
f

array([[0.3548147 , 0.58877581, 0.9457374 , 0.62661019, 0.34248117],
       [0.46856743, 0.21504962, 0.19990668, 0.89649817, 0.87380934],
       [0.58687786, 0.24693419, 0.16308014, 0.00350304, 0.7418776 ],
       [0.72722971, 0.12133842, 0.99629148, 0.27774802, 0.49212808],
       [0.59849849, 0.19431807, 0.78705051, 0.90241619, 0.71103124],
       [0.97580372, 0.45821386, 0.82328005, 0.81484171, 0.43772819]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [47]:
n_array = np.array([[55, 25, 15,22], 
                    [30, 44, 2,33], 
                    [11, 45, 77,44],
                     [22,34,56,55]])
b=np.diagonal(n_array)
print(sum(b))

231


## Question:13

### Find the determinant of the previous array in Q12?

In [48]:
det = np.linalg.det(n_array)
print(int(det))

2966700


## Question:14

### Find the 5th and 95th percentile of an array?

In [49]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.percentile(a,5)
c=np.percentile(a,95)
print("5th percentile is= ",  b ,"The 95th percentile is =" , c)

5th percentile is=  1.4 The 95th percentile is = 8.6


## Question:15

### How to find if a given array has any null values?

In [20]:
a=np.array([1,2,3,4])
b=np.isnan(a)
b

array([False, False, False, False])